export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'

export const SET_CURRENT_DEPTH = 'SET_CURRENT_DEPTH'

export const SET_CURRENT_BROWSE_NODE = 'SET_CURRENT_BROWSE_NODE'

export const SET_TITLES = 'SET_TITLES'

export const RESET_DICTIONARY = 'RESET_DICTIONARY'

export const SET_DICTIONARY = 'SET_DICTIONARY'

export const SET_WORD_CLOUD = 'SET_WORD_CLOUD'

export const RESET_DIC_WORD_COUNT = 'RESET_DIC_WORD_COUNT'

// export const SET_SUBMISSIONS = 'SET_SUBMISSIONS'
//
// export const SET_TOP_SELLERS = 'SET_TOP_SELLERS'
//
// export const SET_ATTRIBUTES = 'SET_ATTRIBUTES'
