export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'

export const SET_CURRENT_DEPTH = 'SET_CURRENT_DEPTH'

export const SET_CURRENT_BROWSE_NODE = 'SET_CURRENT_BROWSE_NODE'

export const SET_TITLES = 'SET_TITLES'

// export const SET_SUBMISSIONS = 'SET_SUBMISSIONS'
//
// export const SET_TOP_SELLERS = 'SET_TOP_SELLERS'
//
// export const SET_ATTRIBUTES = 'SET_ATTRIBUTES'
